#!/usr/bin/env bash
echo "Checking Kotlin changed files on Git stage..."
CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2 }')"

if [ -n "$CHANGED_FILES" ]; then
  echo "Kotlin changed files:"
  echo "$CHANGED_FILES"

  echo "Running detekt check..."
  OUTPUT="/tmp/detekt-$(date +%s)"
  echo "$CHANGED_FILES" > "$OUTPUT"
  ./gradlew detekt -PdetektFiles="$(echo "$CHANGED_FILES" | tr '\n' ',')" > "$OUTPUT"
  EXIT_CODE=$?
  if [ $EXIT_CODE -ne 0 ]; then
    cat "$OUTPUT"
    rm "$OUTPUT"
    echo "************************************************"
    echo "                 Detekt failed                  "
    echo "   Please fix the above issues before pushing   "
    echo "************************************************"
    exit $EXIT_CODE
  else
    echo "All Kotlin files passed Detekt!"
  fi
  rm "$OUTPUT"

  echo "Running ktlintCheck to the changed files..."
  ./gradlew ktlintCheck -Pfiles="$CHANGED_FILES"
  EXIT_CODE=$?
  if [ $EXIT_CODE -ne 0 ]; then
    echo "Running ktlintFormat on modified files..."
    ./gradlew ktlintFormat -Pfiles="$CHANGED_FILES"

    echo "Updating git stage..."
    git add "$CHANGED_FILES"
    git status

    echo "Running ktlintCheck again..."
    ./gradlew ktlintCheck -Pfiles="$CHANGED_FILES"
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
      echo "ktlintFormat could not resolve all the issues. Please fix them manually."
      exit 1
    else
      echo "All the issues resolved by ktlintFormat!"
    fi
  else
    echo "All Kotlin files passed ktlintCheck!"
  fi
else
  echo "No Kotlin files changed."
fi
